version: '3'
services:
  tao:
    image: taos
    links:
      - mysql
    ports:
      - "80:80"
    volumes:
      - tao:/home/web
  mysql:
    container_name: mysql-dev
    image: mysql/mysql-server:5.7
    ports:
      - "5306:3306"
    volumes:
      - data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${TAO_MYSQL_PASSWORD}
      MYSQL_USER: ${TAO_MYSQL_USER}
      MYSQL_PASSWORD: ${TAO_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${TAO_MYSQL_DB}
volumes:
  tao:
    driver: local
  data:
    driver: local

